// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 메인 문서 사이드바
  docs: [
    {
      type: 'category',
      label: '시작하기',
      collapsed: false,
      items: [
        'intro',
      ],
    },
    {
      type: 'category',
      label: '📚 FSR 센서 기초',
      collapsed: false,
      items: [
        'basics/intro',
        'basics/what-is-fsr/index',
        'basics/how-it-works/index',
        'basics/electrical-characteristics/index',
        'basics/mechanical-characteristics/index',
        'basics/applications/index',
      ],
    },
    {
      type: 'category',
      label: '🔬 FSR센서의 특성과 활용',
      collapsed: false,
      items: [
        'fsr-characteristics/intro',
        'fsr-characteristics/what-is-fsr-sensor',
      ],
    },
    {
      type: 'category',
      label: '📦 제품 카탈로그',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'products',
        },
      ],
    },
    {
      type: 'category',
      label: '🔧 기술 문서',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'technical-docs',
        },
      ],
    },
    {
      type: 'category',
      label: '🎓 튜토리얼',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials',
        },
      ],
    },
  ],

  // 자동 생성 사이드바 (필요시 사용)
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
